# Generated by Django 4.2.30 on 2026-06-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('feed_type', models.CharField(choices=[('ip', 'IP'), ('domain', '域名'), ('mixed', '混合')], max_length=16, verbose_name='数据类型')),
                ('url', models.URLField(max_length=500, verbose_name='下载地址')),
                ('format', models.CharField(choices=[('text', '纯文本'), ('csv', 'CSV'), ('json', 'JSON'), ('misp', 'MISP')], default='text', max_length=32, verbose_name='数据格式')),
                ('auth_type', models.CharField(choices=[('none', '无需认证'), ('api_key', 'API Key'), ('header', '自定义 Header')], default='none', max_length=16, verbose_name='认证方式')),
                ('auth_key', models.CharField(blank=True, default='', max_length=256, verbose_name='API Key')),
                ('auth_header_template', models.CharField(blank=True, default='', max_length=256, verbose_name='Header 模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('interval_minutes', models.IntegerField(default=1440, verbose_name='同步间隔(分钟)')),
                ('retry_count', models.IntegerField(default=3, verbose_name='重试次数')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='超时(秒)')),
                ('confidence_base', models.IntegerField(default=50, verbose_name='基础置信度')),
                ('category_default', models.CharField(blank=True, default='', max_length=64, verbose_name='默认分类')),
                ('filter_private', models.BooleanField(default=True, verbose_name='过滤私有地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_status', models.CharField(choices=[('never', '未同步'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='never', max_length=16, verbose_name='最后同步状态')),
                ('last_sync_count', models.IntegerField(default=0, verbose_name='上次同步数')),
                ('total_sync_count', models.IntegerField(default=0, verbose_name='累计同步数')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续失败')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '情报源',
                'verbose_name_plural': '情报源',
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('ip', 'IP'), ('domain', '域名')], max_length=32, verbose_name='同步类型')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=16, verbose_name='状态')),
                ('message', models.TextField(blank=True, default='', verbose_name='消息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.sourcefeed', verbose_name='情报源')),
            ],
            options={
                'verbose_name': '同步记录',
                'verbose_name_plural': '同步记录',
            },
        ),
        migrations.AddIndex(
            model_name='sourcefeed',
            index=models.Index(fields=['slug'], name='sync_source_slug_5f54cb_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefeed',
            index=models.Index(fields=['is_active'], name='sync_source_is_acti_f0e17c_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefeed',
            index=models.Index(fields=['last_sync_at'], name='sync_source_last_sy_698229_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['source'], name='sync_source_source__b1a227_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['started_at'], name='sync_source_started_8ef5e2_idx'),
        ),
    ]
