# Generated by Django 4.2.30 on 2026-06-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=64, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('current_item', models.CharField(blank=True, default='', max_length=255, verbose_name='当前条目')),
                ('message', models.TextField(blank=True, default='', verbose_name='消息')),
                ('cancel_flag', models.BooleanField(default=False, verbose_name='取消标志')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='结果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务进度',
                'verbose_name_plural': '任务进度',
            },
        ),
    ]
