# Generated by Django 4.2.30 on 2026-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='例如 172.21.40.0/24 或 192.168.1.0/24', max_length=43, unique=True, verbose_name='IP 段（CIDR）')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '允许访问的 IP 段',
                'verbose_name_plural': '允许访问的 IP 段',
                'ordering': ['cidr'],
            },
        ),
    ]
