# Generated by Django 4.2.30 on 2026-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaliciousDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='域名')),
                ('prefix_at', models.BooleanField(default=False, help_text='是否带 @ 前缀（匹配子域名）', verbose_name='@ 前缀')),
                ('source', models.CharField(db_index=True, default='manual', max_length=64, verbose_name='来源')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '恶意域名',
                'verbose_name_plural': '恶意域名',
                'indexes': [models.Index(fields=['domain'], name='risk_domain_domain_96db12_idx'), models.Index(fields=['source'], name='risk_domain_source_09828d_idx'), models.Index(fields=['is_active'], name='risk_domain_is_acti_f0cf6b_idx')],
            },
        ),
    ]
