# Generated by Django 4.2.30 on 2026-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaliciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP 地址')),
                ('cidr', models.CharField(blank=True, max_length=43, null=True, unique=True, verbose_name='CIDR')),
                ('range_start', models.GenericIPAddressField(blank=True, null=True, verbose_name='范围起始')),
                ('range_end', models.GenericIPAddressField(blank=True, null=True, verbose_name='范围结束')),
                ('source', models.CharField(db_index=True, default='manual', max_length=64, verbose_name='来源')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='分类')),
                ('confidence', models.IntegerField(default=0, verbose_name='置信度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '恶意 IP',
                'verbose_name_plural': '恶意 IP',
                'indexes': [models.Index(fields=['ip_address'], name='risk_ip_mal_ip_addr_5a1a2a_idx'), models.Index(fields=['source'], name='risk_ip_mal_source_53c946_idx'), models.Index(fields=['category'], name='risk_ip_mal_categor_700827_idx'), models.Index(fields=['is_active'], name='risk_ip_mal_is_acti_530e27_idx'), models.Index(fields=['created_at'], name='risk_ip_mal_created_5fe806_idx')],
            },
        ),
    ]
