# Generated by Django 4.2.30 on 2026-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True, verbose_name='标识')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='颜色')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='maliciousip',
            name='tags',
            field=models.ManyToManyField(blank=True, to='risk_ip.tag', verbose_name='标签'),
        ),
    ]
