# Generated by Django 4.2.30 on 2026-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_ip', '0002_tag_maliciousip_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True, verbose_name='标识')),
                ('is_manual', models.BooleanField(default=False, help_text='手动输入 vs 自动同步', verbose_name='手动来源')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '来源预设',
                'verbose_name_plural': '来源预设',
                'ordering': ['name'],
            },
        ),
    ]
