# Generated by Django 4.2.30 on 2026-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('mac_address', models.CharField(blank=True, default='', help_text='格式: xx:xx:xx:xx:xx:xx', max_length=17, verbose_name='MAC 地址')),
                ('hostname', models.CharField(blank=True, default='', max_length=128, verbose_name='主机名')),
                ('person_name', models.CharField(blank=True, default='', max_length=64, verbose_name='姓名')),
                ('department', models.CharField(blank=True, default='', max_length=128, verbose_name='部门')),
                ('device_type', models.CharField(choices=[('computer', '电脑'), ('printer', '打印机'), ('router', '路由器'), ('server', '服务器'), ('other', '其他')], default='computer', max_length=32, verbose_name='设备类型')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本地资产',
                'verbose_name_plural': '本地资产',
                'indexes': [models.Index(fields=['ip_address'], name='local_asset_ip_addr_2951a4_idx'), models.Index(fields=['person_name'], name='local_asset_person__16f946_idx'), models.Index(fields=['department'], name='local_asset_departm_0a5fb9_idx'), models.Index(fields=['mac_address'], name='local_asset_mac_add_de7afb_idx')],
            },
        ),
    ]
